name: Build and Release

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
    contents: read
    pull-requests: write

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [linux, windows-latest, macOS-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go

    - name: Setup Fyne
      run: go install fyne.io/fyne/v2/cmd/fyne@latest

    - name: Build
      run: fyne package -os ${{ matrix.os }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: deps-cleaner-${{ matrix.os }}
        path: dist/deps-cleaner-${{ matrix.os }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release:
          - Add new feature
          - Fix bugs
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Artifact
      uses: actions/download-artifact@v2
      with:
        name: deps-cleaner-${{ matrix.os }}
        path: dist

    - name: Upload Artifact
      uses: actions/upload-release-asset@v1.0.1
      with:
        asset_path: dist/deps-cleaner-${{ matrix.os }}
        asset_name: deps-cleaner-${{ matrix.os }}
        asset_content_type: application/octet-stream
        release_id: ${{ steps.create_release.outputs.release_id }}
        token: ${{ secrets.GITHUB_TOKEN }}
