name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: |
            build/dist/**/*
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
          tag: ${{ github.ref }}
